### PR TITLE
fbw: use non absolute wget path

### LINKED ISSUE #798: FBW: hardcoded wget absolute path is wrong on OpenWrt 19.07
In OpenWrt 18.06 `wget` link pointing to uclient-fetch was located in `/bin/`, [see here](https://github.com/openwrt/openwrt/blob/openwrt-18.06/package/libs/uclient/Makefile#L46), but in OpenWrt 19.07 this was moved to `/usr/bin/`, [see here](https://github.com/openwrt/openwrt/blob/openwrt-19.07/package/libs/uclient/Makefile#L35).

For this reason, two wget commands are failing inside FirstBootWizard:
https://github.com/libremesh/lime-packages/blob/31e6a58d36ca637fab640f423df42ce7363a2677/packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua#L160

https://github.com/libremesh/lime-packages/blob/31e6a58d36ca637fab640f423df42ce7363a2677/packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua#L166

### PR DESCRIPTION
**Pull request by spiccinini**
wget path changed from 18.06 to 19.07 so this is to be more compatible.
Current uses of firstbootwizard (init.d and ubus daemon) have the PATH
env variable correctly populated so this should not break anything.

Fixes #798

### CODE REVIEW

File: packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua [hunk 1]
```diff
@@ -157,13 +157,13 @@ end
 function fbw.fetch_config(data)
     fbw.log('Fetch config from '.. json.stringify(data))
     local host = data.host
```
Comment (G10h4ck) [inline packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua:159]: either we avoid to define this local variable or later we use `host` instead of `data.host`

**Review by G10h4ck — APPROVED** [review]

**Review by ilario — APPROVED** [review]
Tested on top of Openwrt 19.07.4. Using this patch and manually fixing #807, FBW works.
